import datetime
import os
from dotenv import load_dotenv
from google import genai
import time

load_dotenv()

API_KEY = os.getenv("GOOGLE_GENAI_API_KEY")
THINKING_BUDGET = 8192
TEMPERATURE = 0.8
MODEL = "gemini-2.5-flash-preview-09-2025"

system_instruction = '''
You are a sophisticated AI expert in IT skill taxonomy and curriculum design. Your task is to process a list of IT skill names and enrich it into a structured JSON format. You will analyze each skill and determine its proficiency level, key components, and essential prerequisites based on common industry standards.
'''

prompt = '''
[
    "JavaScript",
    "cloud security and compliance",
    "system backup best practice",
    "ICT system programming",
    "computer engineering",
    "DevOps",
    "cloud technologies",
    "Jenkins (tools for software configuration management)",
    "integrated development environment software",
    "software frameworks",
    "cloud monitoring and reporting",
    "ASP.NET",
    "Eclipse (integrated development environment software)",
    "ICT project management methodologies",
    "application usability",
    "KDevelop",
    "Agile development",
    "ICT architectural frameworks",
    "Agile project management",
    "information governance compliance",
    "DB2",
    "information security strategy",
    "internal risk management policy",
    "ICT security legislation",
    "business process modelling",
    "database",
    "web programming",
    "resource description framework query language",
    "database management systems",
    "systems theory",
    "information structure",
    "query languages",
    "data warehouse",
    "database development tools",
    "Smalltalk (computer programming)",
    "Perl",
    "SAS language",
    "Java (computer programming)",
    "C++",
    "product data management",
    "MarkLogic",
    "C#",
    "MySQL",
    "TypeScript",
    "AJAX",
    "lean project management",
    "LDAP",
    "Microsoft Access",
    "Objective-C",
    "Lisp",
    "unstructured data",
    "SQL Server",
    "data science",
    "Haskell",
    "OpenEdge Database",
    "R",
    "Common Lisp",
    "data visualisation software",
    "Visual Basic",
    "Prolog (computer programming)",
    "Swift (computer programming)",
    "Scratch (computer programming)",
    "IBM Informix",
    "APL",
    "Erlang",
    "Scala",
    "Process-based management",
    "LINQ",
    "SAP R3",
    "VBScript",
    "COBOL",
    "PHP",
    "Pascal (computer programming)",
    "N1QL",
    "Microsoft Visual C++",
    "Teradata Database",
    "data models",
    "OpenEdge Advanced Business Language",
    "ABAP",
    "SPARQL",
    "CA Datacom/DB",
    "CoffeeScript",
    "PostgreSQL",
    "ObjectStore",
    "Python (computer programming)",
    "TripleStore",
    "Ruby (computer programming)",
    "ML (computer programming)",
    "XQuery",
    "MATLAB",
    "computer programming",
    "Groovy",
    "Filemaker (database management systems)",
    "Oracle Relational Database",
    "Assembly (computer programming)",
    "MDX",
    "hardware testing methods",
    "Internet of Things",
    "principles of artificial intelligence",
    "machine learning",
    "mechatronics",
    "ICT software specifications",
    "task algorithmisation",
    "algorithms",
    "computer science",
    "computer technology",
    "mobile device software frameworks",
    "decentralized application frameworks",
    "service-oriented modelling",
    "JavaScript Framework",
    "IBM WebSphere",
    "data storage",
    "data analytics",
    "statistics",
    "SAS Data Management",
    "levels of software testing",
    "visual presentation techniques",
    "ICT performance analysis methods",
    "decision support systems",
    "ICT debugging tools",
    "tools for ICT test automation",
    "ICT quality policy",
    "software anomalies",
    "quality assurance methodologies",
    "ICT process quality models",
    "quality standards",
    "data quality assessment",
    "database quality standards",
    "usability engineering",
    "systems development life-cycle",
    "ICT security standards",
    "engineering processes",
    "product life-cycle",
    "organisational resilience",
    "audit techniques",
    "legal requirements of ICT products",
    "ICT project management",
    "World Wide Web Consortium standards",
    "ICT network security risks",
    "cyber security",
    "ICT accessibility standards",
    "3D texturing",
    "tools for software configuration management",
    "digital game genres",
    "computer graphics",
    "3D lighting",
    "Xcode",
    "Ansible",
    "augmented reality",
    "Joomla",
    "Puppet (tools for software configuration management)",
    "STAF",
    "Apache Maven",
    "trigonometry",
    "Salt (tools for software configuration management)",
    "object-oriented modelling",
    "interactive media",
    "ICT network routing",
    "network standards",
    "network engineering",
    "system design",
    "ICT networking hardware",
    "ICT network simulation",
    "network management system tools",
    "attack vectors",
    "internet governance",
    "Cisco",
    "procurement of ICT network equipment",
    "industrial software",
    "embedded systems",
    "mobile operating systems",
    "screen reader",
    "iOS",
    "BlackBerry",
    "trading software",
    "Android (mobile operating systems)",
    "security engineering",
    "ICT recovery techniques",
    "ethical hacking principles",
    "core banking software",
    "ICT system user requirements",
    "human-computer interaction",
    "ICT sales methodologies",
    "ICT system integration",
    "copyright legislation",
    "emergent technologies",
    "software components libraries",
    "game theory",
    "hardware components",
    "style sheet languages",
    "software UI design patterns",
    "graphics editor software",
    "LESS",
    "Synfig",
    "SketchBook Pro",
    "Ajax Framework",
    "Sass",
    "Microsoft Visio",
    "JSSS",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "WordPress",
    "Drupal",
    "software interaction design",
    "CSS",
    "GIMP (graphics editor software)",
    "Vagrant",
    "NoSQL",
    "business strategy concepts",
    "ICT market",
    "information architecture",
    "Iterative development",
    "business requirements techniques",
    "Prototyping development",
    "incremental development",
    "software design methodologies",
    "Spiral development",
    "unified modelling language",
    "Rapid application development",
    "Waterfall development",
    "software architecture models",
    "digital systems",
    "inter-organisational middleware system",
    "interfacing techniques",
    "consultation methods",
    "digital image processing",
    "computer simulation",
    "image recognition",
    "scientific computing",
    "digital twin technology",
    "data engineering",
    "image formation",
    "deep learning",
    "state estimation",
    "signal processing",
    "mathematical modelling",
    "quantum computing",
    "cognitive computing",
    "real-time computing",
    "engineering control theory",
    "ICT communications protocols",
    "SPARK",
    "field-programmable gate arrays",
    "battery management systems",
    "hardware architectures",
    "operating systems",
    "ICT infrastructure",
    "domain name service",
    "organisational policies",
    "Apache Tomcat",
    "data extraction, transformation and loading tools",
    "Oracle Application Development Framework",
    "QlikView Expressor",
    "Oracle Warehouse Builder",
    "SQL Server Integration Services",
    "SAP Data Services",
    "ICT power consumption",
    "Pentaho Data Integration",
    "Oracle Data Integrator",
    "IBM InfoSphere Information Server",
    "SQL",
    "IBM InfoSphere DataStage",
    "Informatica PowerCenter",
    "blueprints",
    "statistical process control",
    "quality and cycle time optimisation",
    "CAD software",
    "mathematics",
    "lathe machine parts",
    "electrical engineering",
    "manufacturing processes",
    "3D modelling",
    "engineering principles",
    "mechanics",
    "business intelligence",
    "cyber attack counter-measures",
    "risk management",
    "security threats",
    "assessment of risks and threats",
    "hybrid model",
    "mobile device management",
    "ICT problem management techniques",
    "Outsourcing model",
    "information confidentiality",
    "ICT encryption",
    "web application security threats",
    "investment analysis",
    "Open source model",
    "computer forensics",
    "web services",
    "model based system engineering",
    "hardware components suppliers",
    "software components suppliers",
    "web based collaborative platforms",
    "cognitive psychology",
    "natural language processing",
    "WildFly",
    "project configuration management",
    "Chef (tools for software configuration management)",
    "control objectives for information and related technology",
    "Codenvy",
    "Octopus Deploy",
    "scientific research methodology",
    "data mining",
    "innovation processes",
    "digitization",
    "behavioural science",
    "operational research",
    "mathematical physics",
    "documentation types",
    "information extraction",
    "computational biology",
    "information categorisation",
    "data ethics",
    "healthcare analytics",
    "business processes",
    "content development processes",
    "keywords in digital content",
    "authoring software",
    "publishing strategy",
    "content marketing strategy",
    "defence standard procedures",
    "blockchain openness",
    "smart contract",
    "blockchain platforms",
    "Oracle WebLogic",
    "telecom regulations",
    "artificial neural networks",
    "computer vision",
    "business analytics",
    "web analytics",
    "online analytical processing",
    "research design",
    "multidisciplinary research",
    "statistical modeling techniques",
    "marketing analytics",
    "Hadoop",
    "social network analysis",
    "building systems monitoring technology",
    "ethics",
    "penetration testing tool",
    "OWASP ZAP",
    "John The Ripper (penetration testing tool)",
    "Maltego",
    "proxy servers",
    "Aircrack (penetration testing tool)",
    "WhiteHat Sentinel",
    "Metasploit",
    "Kali Linux",
    "Backbox (penetration testing tool)",
    "Nexpose",
    "Nessus",
    "Cain and Abel (penetration testing tool)",
    "Wireshark",
    "Samurai Web Testing Framework",
    "Parrot Security OS",
    "BlackArch",
    "WebCMS",
    "crowdsourcing strategy",
    "statistical analysis system software",
    "outsourcing strategy",
    "ICT capacity planning strategies",
    "insourcing strategy",
    "labour legislation",
    "sustainable technologies",
    "ICT environmental policies",
    "green building standards",
    "resource-efficient technologies",
    "sustainability consulting",
    "corporate sustainability",
    "hardware platforms",
    "project management",
    "technical drawings",
    "distributed computing",
    "product usage risks analysis",
    "software metrics",
    "online moderation techniques",
    "sales strategies",
    "social media marketing techniques",
    "mobile marketing",
    "digital marketing techniques",
    "safety engineering",
    "business ICT systems",
    "solution deployment",
    "quantitative analysis",
    "empirical analysis",
    "scientific literature",
    "digital curation",
    "incidents and accidents recording",
    "GDPR",
    "operational tactics for emergency responses",
    "leadership principles",
    "check methods",
    "forensic intelligence",
    "THC Hydra",
    "data protection"
]

Generate a JSON array where each main skill is an object with the following structure:
{
    "knowledge": "<skill_name>",
    "level": "<level, from 1 to 10>",
    "detailed": ["List of detailed knowledge areas related to the main knowledge, like framework, library, protocols, ... Eg for 'JavaScript Framework' it could be ['React', 'Node.js', 'Vue.js']"],
    "prerequisites": ["<list_of_prerequisite_skills. Only main skill is needed here, no detailed knowledge areas>"]
}

FIELD DEFINITIONS & CONSTRAINTS:
skill (string): The name of the skill, copied exactly from the input.
level (integer): An integer from 1 to 10 representing the typical proficiency level required for a professional role centered around this skill. Use this scale for consistency:
1-2: Foundational/Academic knowledge.
3-4: Junior-level proficiency; can perform basic tasks with supervision.
5-6: Mid-level/Professional proficiency; can work independently on most tasks.
7-8: Senior-level/Advanced proficiency; can lead projects and mentor others.
9-10: Expert/Architect-level mastery; recognized as a thought leader, can innovate and set strategy.
detailed (array of strings): A list of 5 to 7 of the most critical sub-skills, technologies, or core concepts that define this skill. Be specific and focus on the most important components.
prerequisites (array of strings): A list of 1 to 3 direct, foundational skills required before someone can effectively learn the main skill. Only list the absolute most important prerequisites. Do not make up the main skill that are not in the provided list.
prerequisites should not form a cycle. If a cycle is formed, make all the prerequisites in the cycle the same level.

Only include smaller skills that are relevant to IT professionals and exclude any non-IT related skills. 
Do not make up the main skill that are not in the provided list.
Output in JSON format. Only output like a JSON file. Do not include any Markdown elements or code blocks.
'''

client = genai.Client(api_key=API_KEY)

start_time = time.perf_counter()
response = client.models.generate_content(
    model=MODEL, 
    contents=prompt,
    config=genai.types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=TEMPERATURE,
        thinking_config=genai.types.ThinkingConfig(thinking_budget=THINKING_BUDGET)
    ),
)
end_time = time.perf_counter()

try:
    filename: str = f"ailog_projectprompt_{datetime.datetime.now().strftime('%Y-%m-%dT%H-%M-%S')}_{MODEL}_temp{TEMPERATURE}_thinkbudget{THINKING_BUDGET}.txt"
    with open(filename, 'w') as file:
        file.write(response.text)
    print(f"Data written")
except IOError as e:
    print(f"An error occurred: {e}")
    exit(1)

execution_time = end_time - start_time
print(f"The function took {execution_time:.2f} seconds to run.")